/**
 * Pre-build hook: stamps the current build with a fresh ID + date.
 *
 * Writes src/main/build-info.ts which is imported by the main process
 * to expose version metadata over IPC. The build number auto-increments
 * each time this script runs, giving an unambiguous monotonic counter.
 */

const fs = require('node:fs')
const path = require('node:path')

const INFO_PATH = path.join(__dirname, '..', 'src', 'main', 'build-info.ts')
const PKG_PATH = path.join(__dirname, '..', 'package.json')

function readPreviousBuildNumber() {
  if (!fs.existsSync(INFO_PATH)) return 0
  const match = fs.readFileSync(INFO_PATH, 'utf8').match(/BUILD_NUMBER\s*=\s*(\d+)/)
  return match ? parseInt(match[1], 10) : 0
}

function main() {
  const pkg = JSON.parse(fs.readFileSync(PKG_PATH, 'utf8'))
  const buildNumber = readPreviousBuildNumber() + 1
  const now = new Date()
  const stamp = now.toISOString().slice(0, 10).replace(/-/g, '')
  const buildId = `${stamp}.${String(buildNumber).padStart(4, '0')}`

  const content = `// Auto-generated by scripts/bump-build.js. Do not edit manually.
export const APP_VERSION = '${pkg.version}'
export const BUILD_NUMBER = ${buildNumber}
export const BUILD_DATE = '${now.toISOString().slice(0, 10)}'
export const BUILD_ID = '${buildId}'
`

  fs.writeFileSync(INFO_PATH, content)
  console.log(`[bump-build] v${pkg.version} build ${buildId}`)
}

main()
